POST http://localhost:4004/api/nutrition
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "9697034b-58a1-4942-aa1d-dfa2b25e403a",
  "mealType": "BREAKFAST",
  "calories": 450,
  "protein": 30,
  "carbs": 50,
  "fat": 15,
  "date": "2025-12-17"
}

