### Creates a new patient entity
POST http://localhost:4004/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "manjo",
  "email": "manjo.sharma@example.com",
  "address": "123 Main Street, Apt 22",
  "dateOfBirth": "2000-09-09",
  "weight": 60.5,
  "height": 1.65,
  "gender": "FEMALE",
  "fitnessGoal": "LOSE_WEIGHT",
  "dailyStepGoal": 10000,
  "sleepGoalHours": 8.0,
  "notificationsEnabled": true,
  "registeredDate": "2024-11-28"
}

###