##
POST http://localhost:4004/api/activities
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "6ac847c9-ceeb-4b1a-90c5-44f9da40f15f",
  "workoutType": "YOGA",
  "durationMinutes": 45,
  "caloriesBurned": 400,
  "activityDate": "2025-01-15"
}
