##
POST http://localhost:4004/api/activities
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "10add762-8407-4df8-ae08-eb9617e34a26",
  "workoutType": "YOGA",
  "durationMinutes": 45,
  "caloriesBurned": 400,
  "activityDate": "2025-01-15"
}
