##
POST http://localhost:4004/api/activities
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "e84bf175-7e4a-4976-9f72-0388829ae49e",
  "workoutType": "YOGA",
  "durationMinutes": 45,
  "caloriesBurned": 400,
  "activityDate": "2025-01-15"
}
